Repository systemsomicslab/MsdialWorkbench, pull requests merged in 2023-02, with the labels that each got.

#14 Add `How to build this repo` to README
  README.md
Labels: documentation

#29 Add annotation info to exported result.
  src/Common/CommonStandard/DataObj/Result/MsScanMatchResult.cs
  src/MSDIAL5/MsdialCore/Export/IAnalysisMetadataAccessor.cs
  src/MSDIAL5/MsdialCore/Export/IMetadataAccessor.cs
  tests/MSDIAL5/MsdialCoreTests/Export/BaseAnalysisMetadataAccessorTests.cs
  tests/MSDIAL5/MsdialCoreTests/Export/BaseMetadataAccessorTests.cs
Labels: enhancement

#28 Add spectrum shifting function to Spectrumviewer application.
  MsdialWorkbench.sln
  src/MSDIAL5/SpectrumViewer/Model/DisplayScan.cs
  src/MSDIAL5/SpectrumViewer/Model/SplitSpectrumsModel.cs
  src/MSDIAL5/SpectrumViewer/View/ViewTemplates.xaml
  src/MSDIAL5/SpectrumViewer/ViewModel/DisplayScanViewModel.cs
  src/MSDIAL5/SpectrumViewer/ViewModel/SplitSpectrumsViewModel.cs
Labels: enhancement

#30 Fix a data binding bug of the NumericUpDown control.
  src/Common/ChartDrawing/UI/NumericUpDown.cs
  tests/Common/ChartDrawingUiTest/UI/NumericUpDownTest.xaml
Labels: bug
